#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

#- For non-parallel running
cp -r 0.org 0 &> /dev/null

#- For parallel running
# ls -d processor* | xargs -i rm -rf ./{}/0
# ls -d processor* | xargs -i cp -r 0.org ./{}/0

runApplication $(getApplication)
# ----------------------------------------------------------------- end-of-file
